
import React from 'react';
import { ShieldAlert } from 'lucide-react';

const Legal = () => {
  return (
    <section id="disclaimer" className="py-24 bg-cyber-dark relative overflow-hidden">
      {/* Background effect */}
      <div className="absolute top-0 left-0 w-full h-20 bg-gradient-to-b from-cyber-black to-transparent"></div>
      <div className="absolute bottom-0 left-0 w-full h-20 bg-gradient-to-t from-cyber-black to-transparent"></div>
      
      {/* Glow effect */}
      <div className="absolute top-1/2 left-1/4 w-[400px] h-[400px] rounded-full bg-cyber-purple/5 blur-[100px] pointer-events-none" />
      
      <div className="max-w-4xl mx-auto px-6 relative z-10">
        <div className="text-center mb-12">
          <h2 className="inline-flex items-center space-x-2 py-1 px-3 rounded-full bg-cyber-blue/10 border border-cyber-blue/20 text-xs font-medium text-white mb-4">
            <ShieldAlert className="w-4 h-4 text-cyber-red" />
            <span>Legal Information</span>
          </h2>
          <h3 className="text-3xl md:text-4xl font-bold text-white mb-4">Legal <span className="text-gradient-purple">Disclaimer</span></h3>
        </div>

        <div className="cyber-card p-8 rounded-lg space-y-6 opacity-0 animate-slide-up">
          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Educational and Research Purposes</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              PPT Presentation Crafter is designed for informational, educational, and research purposes only. This tool is intended to assist users in learning about presentation creation and exploring AI-powered content generation capabilities.
            </p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Disclaimer of Liability</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              PPT Presentation Crafter is provided "as is" without any warranties, expressed or implied. AI WEB TOOLS LLC makes no representations or warranties of any kind concerning the safety, suitability, lack of viruses, inaccuracies, typographical errors, or other harmful components of this software. You use the software at your own risk, and AI WEB TOOLS LLC shall not be liable for any damages of any kind resulting from the use of this software.
            </p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Content Responsibility</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              The presentations, visual elements, and content generated by PPT Presentation Crafter are created using artificial intelligence. While we strive to produce accurate and high-quality content, we cannot guarantee the accuracy, completeness, or reliability of the generated content. Users are responsible for reviewing and verifying all content before use, especially for professional, academic, or commercial purposes.
            </p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Intellectual Property</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              Presentations created using PPT Presentation Crafter are owned by the user. However, the software, including its algorithms and models, is owned by AI WEB TOOLS LLC. Users are granted a non-exclusive license to use the generated content but may not reverse engineer, modify, or distribute the software itself. The images generated by DALL-E are subject to OpenAI's usage policies.
            </p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Data Privacy</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              By using PPT Presentation Crafter, you acknowledge that your inputs and generated content may be processed by AI models. We recommend not inputting confidential or sensitive information. For more information on how your data is handled, please refer to our <a href="https://openai.com/policies/privacy-policy/" className="text-cyber-blue hover:underline">Privacy Policy</a>.
            </p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Third-Party Services</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              PPT Presentation Crafter utilizes third-party services including OpenAI's language and image generation models. Use of these services is subject to their respective terms of service. AI WEB TOOLS LLC is not responsible for the availability or functionality of these third-party services.
            </p>
          </div>

          <div className="space-y-4">
            <h4 className="text-xl font-semibold text-white">Terms of Service</h4>
            <p className="text-white/70 text-sm leading-relaxed">
              By using this software, you agree to comply with all applicable laws and regulations and to be bound by our <a href="https://aiwebtools.lovable.app/disclaimers" className="text-cyber-blue hover:underline">Terms of Service</a>.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Legal;
